#!/bin/bash
#
# Generate state transition diagram for Hadoop daemons

mvn compile -Pvisualize
for f in *.gv; do dot -Tpng $f > $(basename $f .gv).png; done
cp *.png ~/hadoop-state-machine-diagrams
open ~/hadoop-state-machine-diagrams/*.png
