#!/bin/bash
#
# Start a single-node Hadoop MR1 cluster

if [ ! -e bin/hadoop ]; then
  echo Not in a Hadoop directory
  exit 1
fi
cp ~/.hadoop/conf/* conf
export HADOOP_HOME=$(pwd)
echo $HADOOP_HOME > ~/.hadoop/HADOOP_HOME
#rm -rf /tmp/hadoop-$USER
bin/start-mapred.sh
sleep 2
open http://localhost:50030
